// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkcboceaucqsppwpzwah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrY2JvY2VhdWNxc3Bwd3B6d2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDUzNzcsImV4cCI6MjA2ODg4MTM3N30.LjFcclY-kuyNThajmmeeQlM7yWc9gweyPeM2GQiKLlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});